name: Model Collection
description: Submit a model to the inventory.
title: "[Model Collection]: "
labels: ["enhancement"]
body:
  - type: input
    attributes:
      label: "Provider"
      description: "The organization that created the model. (e.g., openai, meta)"
      placeholder: "openai"
    validations:
      required: true

  - type: input
    attributes:
      label: "Model Family"
      description: "The base name for the model series (e.g., Llama 3, Gemma, GPT-4)."
      placeholder: "Gemma"
    validations:
      required: true

  - type: input
    attributes:
      label: "Model ID"
      description: "The ID of the model, you can find it in the model's API documentation, example: ID of GPT-4o is `gpt-4o`"
      placeholder: "o4-mini"
    validations:
      required: true

  - type: input
    attributes:
      label: "Model URL"
      description: "URL of the model's repository, if not applicable, link to the official model card or product page."
      placeholder: "https://huggingface.co/google/gemma-3n-E4B-it"

  - type: input
    attributes:
      label: "Release Date"
      description: "The date the model was publicly released."
      placeholder: "YYYY-MM-DD"

  - type: input
    attributes:
      label: "Context Window (Tokens)"
      description: "Maximum number of tokens in a single request."
      placeholder: "8192"

  - type: input
    attributes:
      label: "Training Data Cutoff"
      description: "The knowledge cutoff date for the model's training data."
      placeholder: "YYYY-MM"

  - type: input
    id: license
    attributes:
      label: "License"
      description: "The software license for the model."
      placeholder: "Apache 2.0"

  - type: checkboxes
    attributes:
      label: "Model Capabilities"
      description: "The capabilities of the model."
      options:
        - label: "streaming"
        - label: "reasoning"
        - label: "tool-calling"

  - type: checkboxes
    attributes:
      label: "Model Input Modalities"
      description: "The input modalities of the model."
      options:
        - label: "text"
        - label: "image"
        - label: "audio"
        - label: "video"
        - label: "vector"

  - type: checkboxes
    attributes:
      label: "Model Output Modalities"
      description: "The output modalities of the model."
      options:
        - label: "text"
        - label: "image"
        - label: "json"
        - label: "audio"
        - label: "video"
        - label: "vector"

  - type: checkboxes
    attributes:
      label: "Model Endpoints"
      description: "Supported API endpoints of the model."
      options:
        - label: "chat-completion"
        - label: "completion"
        - label: "embedding"
        - label: "image-generation"
        - label: "audio-speech"
        - label: "audio-music"

  - type: textarea
    attributes:
      label: "Additional Information"
      description: "Any other relevant details, such as benchmark performance (MMLU, GSM8K), architectural notes, etc."
      placeholder: "MMLU score: 86.4%"
